apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment #the name of the Deployment running in our cluster
spec:
  replicas: 1 # replicas is the number of pods we want to create
  selector:
    matchLabels: #looks at all the created pods and finds one with label 'app' matching 'event-bus' 
      app: event-bus #label
  template: # describes how the pod(s) should be created by the Deployment
    metadata:
      labels:  
        app: event-bus # an identifier/label for the pod that will be created by the Deployment
    spec:  #specification of the pod to be created
      containers:
        - name: event-bus # '-' means array
          image: 23101/event-bus
--- # Marks the end of a configuration / the beginning of another. In this case, we have the Deployment & Service config for a single pod in the same file. 
apiVersion: v1
kind: Service
metadata: 
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP # Even when 'type' is not specified, 'ClusterIP' is used by default.
  ports: 
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005

